# Generated by Django 3.1.6 on 2021-06-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_auto_20210624_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotee',
            name='email',
            field=models.CharField(max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devotee',
            name='fullname',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devotee',
            name='password',
            field=models.CharField(max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devotee',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
