# Generated by Django 3.1.6 on 2021-06-24 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_auto_20210624_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_method', models.CharField(max_length=100)),
                ('proof_payment', models.ImageField(blank=True, null=True, upload_to='profile_pic/Payment/')),
                ('date', models.DateField(auto_now=True)),
                ('devotee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='church.devotee')),
            ],
        ),
    ]
