# Generated by Django 3.1.6 on 2021-06-24 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_auto_20210624_0229'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devotee',
            name='user',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='Devotee',
        ),
    ]
